### PR TITLE
Add typings

### PR DESCRIPTION
**Pull request by Artaud**
Add typings and a test as per issue https://github.com/feathersjs-ecosystem/feathers-mailer/issues/29

Dtslint test passes.

### CODE REVIEW

**Comment by daffl** [comment]
Thank you for doing that! I didn't forget about it, I'll just also need to update the module infrastructure (GitHub actions, updated dependencies) for this plugin before making a release.

**Comment by AshotN** [comment]
@daffl Any chance till will be merged in soon?

**Comment by muhammadyusuf-kurbonov** [comment]
@daffl When can we expect the merge?

**Comment by fratzinger** [comment]
I created a typescript version (see #33). Instead of overloading the constructor, I inferred the `ReturnType` to have typesafe `transporter` and `defaults` based on the first argument provided.

**Comment by Artaud** [comment]
Nice!

**Pull request closed without merging**
